### ISSUE TITLE
MultiJson.load('') behavior doesn't match JSON specification

### ISSUE THREAD

**Issue by joshcooper** [intridea/multi_json#206]
`MultiJson.load('')` raises, but `JSON.load('')` returns `nil`:

```ruby
require 'json'
puts JSON.load('').inspect

require 'multi_json'
MultiJson.use(:json_gem)
begin
  puts MultiJson.load('')
rescue => e
  puts e.class
end
```

```shell
$ bx ruby --version
ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-linux]
$ bx ruby test.rb 
nil
MultiJson::ParseError
```

MultiJson behavior was changed in https://github.com/intridea/multi_json/commit/49aa2d8e12687627199a137123c2c16150af6bb6 to raise an error. But JSON has accepted empty string since 2011 https://github.com/flori/json/commit/0eb6ed53a2cb24d5932690c2206511a0622ab10c Also the [spec](https://datatracker.ietf.org/doc/html/rfc8259) says:

> A [JSON] string is a sequence of zero or more Unicode characters

**Comment by joshcooper** [comment]
It appears `JSON.load` accepts an empty string by default, but `JSON.parse` and `MultiJson.load` do not. Also `JSON.parse` can be configured to reject empty strings:

```
irb(main):001:0> require 'json'
=> true
irb(main):002:0> JSON.load("")
=> nil
irb(main):003:0> JSON.load("", nil, allow_blank: true)
=> nil
irb(main):004:0> JSON.load("", nil, allow_blank: false)
Traceback (most recent call last):
        ....
        3: from /home/josh/work/json/lib/json/common.rb:569:in `load'
        2: from /home/josh/work/json/lib/json/common.rb:216:in `parse'
        1: from /home/josh/work/json/lib/json/common.rb:216:in `parse'
JSON::ParserError (783: unexpected token at '')
irb(main):005:0> JSON.parse("")
Traceback (most recent call last):
        ...
        2: from /home/josh/work/json/lib/json/common.rb:216:in `parse'
        1: from /home/josh/work/json/lib/json/common.rb:216:in `parse'
JSON::ParserError (783: unexpected token at '')
```

I think it would be least surprising if `MultiJson.load` allowed an empty string like the similarly named `JSON.load`, but I don't know if that behavior is universal among different backends.

**Comment by sferik** [comment]
I would accept a patch to make `MultiJson.load` behave like `JSON.load`, however this would require a major version bump.

**Comment by sferik** [comment]
Fixed in https://github.com/sferik/multi_json/commit/8e64edc5acea7f65defb4b1dd6ea0be953f63b55.
